### ISSUE TITLE
Name the CMS

### ISSUE THREAD

**Issue by jerv13** [reliv/rwriter#16]
I would prefer a name like RCM over r-writer or at least something that includes RCM in the title.

**Comment by rodmcnew** [comment]
We already have a ton of code and packagist stuff in the RCM namespace so it would make sense. It also seams to be easier to type and say than rwriter. http://rcmcms.org/?

**Comment by wshafer** [comment]
I like it.  Why beat around the bush.  Reliv Content Manager aka RCM is exactly what it is.  

rcmcms.org seems odd to me, but not a show stopper.  But it says "Reliv Content Manager Content Management System."  That seems redundant.   what about relivcms.org?

**Comment by jerv13** [comment]
RCMS

**Comment by jerv13** [comment]
RelivCMS sounds good too.

**Comment by rodmcnew** [comment]
Ok I created the repo for a website for the CMS at relivcms.github.io

@wshafer has write access to relivcms.github.io in case he want to work on or update it.

I can't grab a top level domain for it today but we can point one at it anytime.

**Comment by rodmcnew** [comment]
relivcms.org sounds like our agreed upon top level doman
