### ISSUE TITLE
RFC: BC Break - CMS to have it's own route

### ISSUE THREAD

**Issue by wshafer** [reliv/rwriter#4]
Hey guys,

Routing through the event listener is quite an issue for existing ZF 2 apps.  It also adds unneeded configuration options.   In order to assist me going forward to make this less intrusive, I'd like to suggest the following change:

Currently the CMS routes are defined like the following:
```
        'contentManager' => [
                'type' => 'Zend\Mvc\Router\Http\Segment',
                'options' => [
                    'route' => '/rcm[/:page][/:revision]',
                    'defaults' => [
                        'controller' => 'Rcm\Controller\IndexController',
                        'action' => 'index',
                    ]
                ],
            ]
```

I'd like to change this to:
```
        'contentManager' => [
                'type' => 'Rcm\Route\Cms',
                'options' => [
                    'route' => '/rcm',
                    'defaults' => [
                        'type' => 'n',
                    ]
                ],
            ]
```

Reason:  This will allow me to fix or remove many of the attached event listeners and use the Route Manager for what's it designed for.  In addition, this will allow the normal 404 error messages to be handled by the default 404 error handler in Zend.

**Comment by rodmcnew** [comment]
I agree RCM should use its own route type rather than the old index controller method. @jerv13 James what do you think?

**Comment by jerv13** [comment]
I am OK with it, submit some code :)

**Comment by jerv13** [comment]
I would like to checkout your code and test it and see the impact before I merge it.

**Comment by wshafer** [comment]
Ok will do.

**Comment by wshafer** [comment]
Change added to reliv/Rcm  Pull request #247.  Please see comments for BC break and migration notes.

**Comment by wshafer** [comment]
@jerv13  - The unit tests are failing, but you should be able to checkout that PR and test against your app.  I'll fix the unit tests and add one for the route, while you're checking this out.
